### PR TITLE
Adding support for @Qualifier annotated parameters. Fixes #22.

### LINKED ISSUE #22: @Qualifier / @BindingAnnotation annotated dependencies are not being injected into hk2 created services
Usually you can use @Named to qualify dependencies:
```
  @Inject
  ColorfulResource(@Named("red") String color)
  {
    this.color = color;
  }
```

But JSR-330 also has support for @Qualifier (http://atinject.googlecode.com/svn/trunk/javadoc/javax/inject/Qualifier.html) , guice also uses @BindingAnnotation (https://github.com/google/guice/wiki/BindingAnnotations)

```
  @Inject
  MyQualifierResource(@Saab Car car)
  {
    this.car = car;
  }

```

### PR DESCRIPTION
**Pull request by jontejj**

### CODE REVIEW

**Comment by rkapsi** [comment]
Thanks for the PR. I can't merge it right away due to formatting problems.

**Comment by jontejj** [comment]
Should I solve them or will you?

**Comment by jontejj** [comment]
Ready for a merge?

**Comment by rkapsi** [comment]
The formatting needs to be fixed before I can merge. I can do it but to give you proper credit for the change it'd be better if you do it.

The formatting is a lose form of Google's https://google-styleguide.googlecode.com/svn/trunk/javaguide.html

**Comment by jontejj** [comment]
I'll look into it tonight.

**Comment by jontejj** [comment]
@rkapsi I fixed the whitespace/formatting issues. Any other things I need to fix?

**Pull request merged**
